server.port=${PORT:8082}

spring.datasource.url=${CUSTOMER_DB_URL:jdbc:postgresql://localhost:5433/customerdb}
spring.datasource.username=${CUSTOMER_DB_USERNAME:postgres}
spring.datasource.password=${CUSTOMER_DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://127.0.0.1:8180/realms/ecommerce-app}

keycloak.base-url=${KEYCLOAK_BASE_URL:http://127.0.0.1:8180}
keycloak.realm=${KEYCLOAK_REALM:ecommerce-app}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:clientApp}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}