spring.application.name=${SPRING_APP_NAME:authservice}

server.port=${PORT:8081}
spring.profiles.active=default


# ================= LOGGING =================

logging.level.org.springframework.security=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=INFO

logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


# ================= SECURITY =================

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:8180/realms/ecommerce-app/protocol/openid-connect/certs}


# ================= ACTUATOR =================

management.endpoints.web.exposure.include=health,info
management.endpoint.gateway.enabled=true


# ================= EUREKA =================

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false





# ================= CUSTOMER SERVICE =================

# Customer Service

spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/CUSTOMER-SERVICE/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


# Product Service

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/PRODUCT-SERVICE/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


# Order Service

spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/ORDER-SERVICE/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Authentication URLs

app.keycloak-realm-url=${KEYCLOAK_REALM_URL:http://127.0.0.1:8180/realms/ecommerce-app}
app.keycloak-client-id=${KEYCLOAK_CLIENT_ID:AuthFlowClient}
app.frontend-callback-url=${FRONTEND_CALLBACK_URL:http://localhost:5173/auth/callback}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}