spring.application.name=product-service

server.port=${PORT:8084}


# PostgreSQL database

spring.datasource.url=${PRODUCT_DB_URL:jdbc:postgresql://localhost:5434/productdb}
spring.datasource.username=${PRODUCT_DB_USERNAME:postgres}
spring.datasource.password=${PRODUCT_DB_PASSWORD}


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# AWS S3

aws.region=${AWS_REGION:eu-north-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:product-images-ecommerce-8687-3722-2921}


# Eureka service registry

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true