--
-- PostgreSQL database dump
--

\restrict 6I31lpogTXcxNys7dFal4EAdn4IvC5CmP0PvMtkgv1OrEozD2eg9Hj4appaXPkk

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.customer DROP CONSTRAINT IF EXISTS customer_pkey;
DROP TABLE IF EXISTS public.customer;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    customerid bigint NOT NULL,
    customer_email character varying(255),
    keycloak_user_id character varying(255),
    customer_name character varying(255),
    shipping_address character varying(255)
);


--
-- Name: customer_customerid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer ALTER COLUMN customerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_customerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: customer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customer (customerid, customer_email, keycloak_user_id, customer_name, shipping_address) FROM stdin;
1	ram.charan@example.com	8aaccea1-90b0-46c6-a854-e03011f87405	Ram Charan	125 Sunset Boulevard, Los Angeles, CA 90028
2	emily.johnson@example.com	39db7397-bdb0-4e27-9406-e99100a500f3	Prabhas Raju	842 Pine Street, Seattle, WA 98101
3	michael.brown@example.com	6efe6fe3-12fd-4265-9830-a8f0f45faacb	Emily Johnson	310 Lakeview Drive, Austin, TX 78701
4	sarah.miller@example.com	ad66024f-572f-4aaf-a852-fe48fe475bbf	Michael Brown	475 Oak Avenue, Chicago, IL 60601
5	james.wilson@example.com	62e5e02b-f137-469c-824b-aae7b6c56270	Sarah Miller	220 Madison Street, New York, NY 10001
6	phoebe.buffay@example.com	f1788368-b52f-4303-880f-49be598aac62	Phoebe Buffay	90 Bedford Street, New York, NY 10014
7	donna.paulsen@example.com	8e665726-144c-4523-b297-a482e7a7ff86	Rachel Green	145 Grove Street, New York, NY 10014
8	sheldon.cooper@example.com	2cee799e-df0a-4474-a5fe-5c901794da7e	Donna Paulsen	625 Park Avenue, New York, NY 10065
9	raj.koothrappali@example.com	5f5ef55a-99f7-4c32-a416-4358d95358fa	Sheldon Cooper	2311 North Los Robles Avenue, Pasadena, CA 91101
10	prabhas@example.com	5bb61428-6c8d-491d-a67a-29ff98bb0c0d	Raj Koothrappali	410 Colorado Boulevard, Pasadena, CA 91101
11	testuser123@gmail.com	56f01287-56aa-4e65-8625-eff6cd448cf4	Test User	123 Main Street
12	duggu.manju1211@gmail.com	e34093d2-4382-432c-a1b2-9d80e8f96e20	Manju	ndknkcn
13	sdj@jnd.com	b1aa5dc6-0924-4368-a2af-59c004aa0f5f	shaja	dnjckekje
14	testuser1234@gmail.com	3e57e37e-1df0-4dca-93a6-c6780db566d1	Test User	123 Main Street
15	manju@gmail.com	4df0470f-0851-4e2b-8bc0-5f3cbe0681e6	manju	bangalore
19	anand.manjama@gmail.com	2ab0458f-1ac8-4828-a9f6-7a5c753a1834	manjukanju	3063 W CHAPMAN AVE
\.


--
-- Name: customer_customerid_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_customerid_seq', 19, true);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (customerid);


--
-- PostgreSQL database dump complete
--

\unrestrict 6I31lpogTXcxNys7dFal4EAdn4IvC5CmP0PvMtkgv1OrEozD2eg9Hj4appaXPkk

