--
-- PostgreSQL database dump
--

\restrict m0wl0TxL0bR4FVMl3f2UaLhPeaOsm7nac4bI85yIWsPm4fZkXCIO22JnYSlPt40

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.order_item DROP CONSTRAINT IF EXISTS fkt4dc2r9nbvbujrljv3e23iibt;
ALTER TABLE IF EXISTS ONLY public.orders DROP CONSTRAINT IF EXISTS orders_pkey;
ALTER TABLE IF EXISTS ONLY public.order_item DROP CONSTRAINT IF EXISTS order_item_pkey;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.order_item;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item (
    id integer NOT NULL,
    name character varying(255),
    price numeric(38,2) NOT NULL,
    quantity integer NOT NULL,
    order_id character varying(255),
    product_id bigint NOT NULL
);


--
-- Name: order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id character varying(255) NOT NULL,
    customer_email character varying(255),
    customer_name character varying(255),
    order_date timestamp(6) without time zone,
    payment_method character varying(255),
    payment_status character varying(255),
    total_price numeric(38,2)
);


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_item (id, name, price, quantity, order_id, product_id) FROM stdin;
1	Wireless Mouse	29.99	1	e3e10e71-94a1-4610-8d21-84e62c841520	1
2	Nike Air Max Running Shoes	129.99	1	e3e10e71-94a1-4610-8d21-84e62c841520	2
3	Samsung 55 Inch 4K Smart TV	649.99	1	3d978827-1758-4053-b8ca-092be6a90745	3
4	Wireless Mouse	29.99	2	6e853c43-f2a8-4931-bb46-a969c362c388	4
5	Nike Air Max Running Shoes	129.99	1	6e853c43-f2a8-4931-bb46-a969c362c388	5
6	computer	299.99	1	c5be0e50-c36b-42de-a712-75e6a58e1201	6
7	loreal	59.99	2	c5be0e50-c36b-42de-a712-75e6a58e1201	7
8	Wireless Mouse	29.99	2	a56849d3-989e-4a35-a78e-17d10a1c8168	8
9	Nike Air Max Running Shoes	129.99	1	a56849d3-989e-4a35-a78e-17d10a1c8168	9
10	Nike Air Max Running Shoes	129.99	2	8f1e64b4-5906-4720-aff6-20e8df63281a	10
11	loreal	59.99	1	30b0d977-e2d7-45a6-8d33-34e097b674a8	11
12	Samsung 55 Inch 4K Smart TV	649.99	1	30b0d977-e2d7-45a6-8d33-34e097b674a8	12
13	Nike Air Max Running Shoes	129.99	1	7523fe70-d850-4868-9858-b10c6037f1d7	13
14	Wireless Mouse	29.99	1	7523fe70-d850-4868-9858-b10c6037f1d7	14
15	Samsung 55 Inch 4K Smart TV	649.99	1	c10614a0-d42e-4b4e-bff8-389234e8a717	15
16	Wireless Mouse	29.99	2	c10614a0-d42e-4b4e-bff8-389234e8a717	16
17	computer	299.99	1	30c64b29-3c8f-4aa3-8326-ca8971830252	17
18	Wireless Mouse	29.99	1	30c64b29-3c8f-4aa3-8326-ca8971830252	18
19	Nike Air Max Running Shoes	129.99	1	a73df803-78d6-45f6-b51b-82cb945b6ae2	19
20	loreal	59.99	1	a73df803-78d6-45f6-b51b-82cb945b6ae2	20
21	Wireless Mouse	29.99	1	a73df803-78d6-45f6-b51b-82cb945b6ae2	21
22	Wireless Mouse	34.99	2	81de8ecb-c371-41c3-9ca6-6b6d9ea101ea	26
23	Wireless Mouse	34.99	2	d53b38d6-fe56-4103-a9cc-2de7e65e954a	26
24	Wireless Mouse	34.99	2	deb86761-7d92-480b-9bd9-4323c963f220	26
25	loreal	59.99	1	5a3a9e61-f50e-49ce-9d52-357ede369736	5
26	Logitech Mechanical Keyboard	89.99	1	5a3a9e61-f50e-49ce-9d52-357ede369736	9
27	loreal	59.99	1	e70862ca-978f-458f-8bbc-2dc24d12187e	5
28	computer	299.99	1	284d27f7-ca4b-417e-b143-91e5c9fba22e	4
29	Logitech Mechanical Keyboard	89.99	2	30970fc7-0277-4d0c-a795-d73fb7383edf	9
30	Wireless Mouse	34.99	1	a2fbaf87-69f1-444a-a033-faa504a3c473	26
31	Wireless Mouse	34.99	1	a6b9129a-49ce-4f33-87ac-109f770b0376	26
32	computer	299.99	1	c6ab94e8-ebf1-47f0-89fd-fd378b3fa626	4
33	Wireless Mouse	29.99	1	c6ab94e8-ebf1-47f0-89fd-fd378b3fa626	1
34	Apple AirPods Pro	249.99	1	0fbceadd-2d80-43e6-bff5-dfcbeb77dd0b	8
35	Lamp	20.00	1	0fbceadd-2d80-43e6-bff5-dfcbeb77dd0b	27
36	Lamp	20.00	1	42dc5b14-3025-448b-b1e0-1826768ab584	27
37	loreal	59.99	1	42dc5b14-3025-448b-b1e0-1826768ab584	5
38	computer	299.99	1	42dc5b14-3025-448b-b1e0-1826768ab584	4
39	loreal	59.99	2	686ed6ba-bdd3-45b2-9cf6-2b12d7c86a3a	5
40	loreal	59.99	1	c0630d4e-2787-4a87-b021-373f1818fdd9	5
41	computer	299.99	1	c0630d4e-2787-4a87-b021-373f1818fdd9	4
42	loreal	59.99	1	5f5ed2cc-a628-40e2-90c8-e1af9e3810ed	5
43	computer	299.99	1	33c4e9b9-9ec3-4d1c-8c9b-ca9107921ea1	4
44	Wireless Mouse	29.99	1	33c4e9b9-9ec3-4d1c-8c9b-ca9107921ea1	1
45	Wireless Mouse	34.99	1	33c4e9b9-9ec3-4d1c-8c9b-ca9107921ea1	26
46	Wireless Mouse	29.99	10	8f0b2b4d-2133-483d-a6ba-3b49e7558cd6	1
47	loreal	59.99	1	8f0b2b4d-2133-483d-a6ba-3b49e7558cd6	5
48	computer	299.99	1	8f0b2b4d-2133-483d-a6ba-3b49e7558cd6	4
49	computer	299.99	2	532f60ef-91a4-43f0-a905-f3327f3cd968	4
50	Pearl Drop Earrings	50.00	1	1065091c-c491-486f-887b-9e467f3b5adc	3
51	Blush Mini Shoulder Bag	200.00	1	1065091c-c491-486f-887b-9e467f3b5adc	2
52	Floral Passport Holder	9.99	1	1065091c-c491-486f-887b-9e467f3b5adc	9
53	Dreamy Wireless Keyboard	49.99	1	1065091c-c491-486f-887b-9e467f3b5adc	8
54	Pearl Drop Earrings	50.00	1	c4bc167e-44b1-4c37-8744-d63b7c5bcec1	3
55	Blush Mini Shoulder Bag	200.00	1	c4bc167e-44b1-4c37-8744-d63b7c5bcec1	2
56	Nova Wireless Mouse	30.00	2	c4bc167e-44b1-4c37-8744-d63b7c5bcec1	1
57	Floral Passport Holder	9.99	3	e74ecd67-980b-4ab9-84c3-08b03cb6d6af	9
58	Floral Summer Dress	49.99	2	27c06e88-f632-4150-8515-5729ba114657	6
59	Nova Wireless Mouse	30.00	2	86f79fa3-3636-4bf0-8167-7899364901f2	1
60	Blush Mini Shoulder Bag	200.00	1	86f79fa3-3636-4bf0-8167-7899364901f2	2
61	Floral Summer Dress	49.99	1	86f79fa3-3636-4bf0-8167-7899364901f2	6
62	Cherry Blossom Candle	9.99	1	1b7dc4d8-cf72-47fe-933e-4f756e74937d	5
63	Berry Glow Lip Oil	19.84	1	1b7dc4d8-cf72-47fe-933e-4f756e74937d	4
64	Nova Wireless Mouse	30.00	2	e15f4195-404a-4bc3-be93-41538af789c7	1
65	Blush Mini Shoulder Bag	200.00	6	82f187e1-faca-41e9-8696-ede1ab227ecb	2
66	Pearl Drop Earrings	50.00	4	82f187e1-faca-41e9-8696-ede1ab227ecb	3
67	Cherry Blossom Candle	9.99	3	82f187e1-faca-41e9-8696-ede1ab227ecb	5
68	Dreamy Wireless Keyboard	49.99	1	82f187e1-faca-41e9-8696-ede1ab227ecb	8
69	Floral Summer Dress	49.99	1	82f187e1-faca-41e9-8696-ede1ab227ecb	6
70	Floral Passport Holder	9.99	1	82f187e1-faca-41e9-8696-ede1ab227ecb	9
71	Blush Mini Shoulder Bag	200.00	2	8b5b3f95-eca4-4b11-8d05-7416cf488480	2
72	Pearl Drop Earrings	50.00	2	72709050-7bae-4e82-93ed-db2d9a433681	3
73	Pearl Drop Earrings	50.00	1	94c61a95-c721-4030-98f4-afaefeb3d02d	3
74	Pearl Drop Earrings	50.00	2	120f4d99-0c14-45b3-bfff-6de66f15e956	3
75	Pearl Drop Earrings	50.00	1	ea492b50-253c-49ac-8f6c-7a221790118b	3
76	Floral Summer Dress	49.99	1	ea492b50-253c-49ac-8f6c-7a221790118b	6
77	Floral Passport Holder	9.99	1	ea492b50-253c-49ac-8f6c-7a221790118b	9
78	Dreamy Wireless Keyboard	49.99	1	ea492b50-253c-49ac-8f6c-7a221790118b	8
79	Pearl Drop Earrings	50.00	2	f661af2b-b15c-4992-ab67-eece5151132f	3
80	Blush Mini Shoulder Bag	200.00	1	d65d8ed0-d8d2-4220-993f-cf74b6407fbd	2
81	Blush Mini Shoulder Bag	200.00	1	41af15cc-c945-413d-be4e-80ec0f6f3cd4	2
82	Floral Passport Holder	9.99	1	b85faf8b-4071-4f62-87e4-809d75337b5b	9
83	Pearl Drop Earrings	50.00	1	1423eacc-3696-4b0c-9adb-56693b201832	3
84	Blush Mini Shoulder Bag	200.00	1	1423eacc-3696-4b0c-9adb-56693b201832	2
85	Blush Mini Shoulder Bag	200.00	4	1f9cef4c-d29c-4a27-8036-7bca6d04097f	2
86	Nova Wireless Mouse	30.00	1	69a33043-994e-44e3-a25c-7ebc439f8ac8	1
87	Blush Mini Shoulder Bag	200.00	1	69a33043-994e-44e3-a25c-7ebc439f8ac8	2
88	Cherry Blossom Candle	9.99	1	69a33043-994e-44e3-a25c-7ebc439f8ac8	5
89	Pearl Drop Earrings	50.00	1	26e0fd49-f7c8-4e93-a8c0-69dc0a7ea280	3
90	Floral Summer Dress	49.99	1	831b2a68-eda5-4005-a28d-c3cac46f45b9	6
91	Floral Passport Holder	9.99	1	831b2a68-eda5-4005-a28d-c3cac46f45b9	9
92	Dreamy Wireless Keyboard	49.99	1	28494d65-4d45-4fc8-a2ee-16ae180b5a7d	8
93	Pearl Drop Earrings	50.00	3	beda68cf-5cea-4b66-80c1-98898bc4dda8	3
94	Floral Summer Dress	49.99	1	beda68cf-5cea-4b66-80c1-98898bc4dda8	6
95	Blush Mini Shoulder Bag	200.00	2	beda68cf-5cea-4b66-80c1-98898bc4dda8	2
96	Nova Wireless Mouse	30.00	1	beda68cf-5cea-4b66-80c1-98898bc4dda8	1
97	Blush Mini Shoulder Bag	200.00	1	b73d758d-3ec4-485d-9eb0-26a715cf0915	2
98	Pearl Drop Earrings	50.00	1	b73d758d-3ec4-485d-9eb0-26a715cf0915	3
99	Cherry Blossom Candle	9.99	5	a9638722-5e7b-4ce2-8dfc-c129ab981f3e	5
100	Blush Mini Shoulder Bag	200.00	1	a9638722-5e7b-4ce2-8dfc-c129ab981f3e	2
101	Floral Summer Dress	49.99	1	a9638722-5e7b-4ce2-8dfc-c129ab981f3e	6
102	Floral Passport Holder	9.99	1	a9638722-5e7b-4ce2-8dfc-c129ab981f3e	9
103	Pearl Drop Earrings	50.00	1	6289a89c-99da-45ca-8b1c-0baa86824453	3
104	Blush Mini Shoulder Bag	200.00	1	b1db01cd-c4ae-43f4-a12f-9bdd4677e19e	2
105	Pearl Drop Earrings	50.00	2	b1db01cd-c4ae-43f4-a12f-9bdd4677e19e	3
106	Floral Summer Dress	49.99	2	b1db01cd-c4ae-43f4-a12f-9bdd4677e19e	6
107	Floral Passport Holder	9.99	1	b1db01cd-c4ae-43f4-a12f-9bdd4677e19e	9
108	Nova Wireless Mouse	30.00	1	a57be472-b270-4937-ba4f-f00f533ffc18	1
109	Pearl Drop Earrings	50.00	3	a08d0ec7-468f-4cd6-86d1-cb55996f50a6	3
110	Floral Passport Holder	9.99	1	907933e5-276f-4231-a2f4-8778ace1abce	9
111	Blush Mini Shoulder Bag	200.00	1	907933e5-276f-4231-a2f4-8778ace1abce	2
112	Pearl Drop Earrings	50.00	1	907933e5-276f-4231-a2f4-8778ace1abce	3
113	Nova Wireless Mouse	30.00	3	907933e5-276f-4231-a2f4-8778ace1abce	1
114	Nova Wireless Mouse	30.00	1	57d58684-0b49-4ac9-8a8e-f9b02338e556	1
115	Nova Wireless Mouse	30.00	1	3803a607-1afd-454a-90ef-8437393e30e1	1
116	Pearl Drop Earrings	50.00	1	45514040-6fad-441c-a474-41ef2d78e981	3
117	Floral Summer Dress	49.99	1	45514040-6fad-441c-a474-41ef2d78e981	6
118	Pearl Drop Earrings	50.00	1	4d627b60-7bc2-4254-982f-70a1592ae333	3
119	Pearl Drop Earrings	50.00	3	e32fd0e3-840a-45da-b611-e449798a3572	3
120	Nova Wireless Mouse	30.00	4	51ceeabf-a29c-4124-8051-4831be5e41d3	1
121	Floral Summer Dress	49.99	1	51ceeabf-a29c-4124-8051-4831be5e41d3	6
122	Nova Wireless Mouse	30.00	1	d5658d18-c85b-4758-9f77-114263a16ef7	1
123	Nova Wireless Mouse	30.00	3	9555f687-fb95-4f7b-900c-3c72c9536f66	1
124	Floral Passport Holder	9.99	1	9555f687-fb95-4f7b-900c-3c72c9536f66	9
125	Pearl Drop Earrings	50.00	1	f1866166-ec99-4546-a451-bf01f4e08537	3
126	Pearl Drop Earrings	50.00	1	0a9d90f0-31d2-45f2-87c8-5d0cf5b668ef	3
127	Pearl Drop Earrings	50.00	1	83c36bb9-d082-45af-896f-7bd8d01098d5	3
128	Rose Gold Necklace & Earrings Set	39.99	1	83c36bb9-d082-45af-896f-7bd8d01098d5	12
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders (id, customer_email, customer_name, order_date, payment_method, payment_status, total_price) FROM stdin;
e3e10e71-94a1-4610-8d21-84e62c841520	ram.charan@example.com	Ram Charan	2026-08-16 18:14:12.739306	CARD	payment successful	159.98
3d978827-1758-4053-b8ca-092be6a90745	emily.johnson@example.com	Prabhas Raju	2026-08-16 18:14:45.313341	CARD	payment successful	649.99
6e853c43-f2a8-4931-bb46-a969c362c388	michael.brown@example.com	Emily Johnson	2026-08-16 18:14:55.27926	PAYPAL	payment successful	189.97
c5be0e50-c36b-42de-a712-75e6a58e1201	sarah.miller@example.com	Michael Brown	2026-08-16 18:15:07.561499	CARD	payment successful	419.97
a56849d3-989e-4a35-a78e-17d10a1c8168	michael.brown@example.com	Emily Johnson	2026-08-16 18:15:16.698909	PAYPAL	payment successful	189.97
8f1e64b4-5906-4720-aff6-20e8df63281a	james.wilson@example.com	Sarah Miller	2026-08-16 18:15:25.59988	APPLE_PAY	payment successful	259.98
30b0d977-e2d7-45a6-8d33-34e097b674a8	phoebe.buffay@example.com	Phoebe Buffay	2026-08-16 18:15:33.630982	CARD	payment successful	709.98
7523fe70-d850-4868-9858-b10c6037f1d7	donna.paulsen@example.com	Rachel Green	2026-08-16 18:15:43.149227	PAYPAL	payment successful	159.98
c10614a0-d42e-4b4e-bff8-389234e8a717	sheldon.cooper@example.com	Donna Paulsen	2026-08-16 18:15:51.346556	CARD	payment successful	709.97
30c64b29-3c8f-4aa3-8326-ca8971830252	raj.koothrappali@example.com	Sheldon Cooper	2026-08-16 18:15:59.132005	CARD	payment successful	329.98
a73df803-78d6-45f6-b51b-82cb945b6ae2	prabhas@example.com	Raj Koothrappali	2026-08-16 18:16:06.547623	PAYPAL	payment successful	219.97
81de8ecb-c371-41c3-9ca6-6b6d9ea101ea	ram.charan@example.com	Ram Charan	2026-08-24 00:11:16.010959	CARD	payment successful	69.98
d53b38d6-fe56-4103-a9cc-2de7e65e954a	ram.charan@example.com	Ram Charan	2026-08-24 00:11:43.669249	CARD	payment successful	69.98
deb86761-7d92-480b-9bd9-4323c963f220	ram.charan@example.com	Ram Charan	2026-08-24 00:12:56.945728	CARD	payment successful	69.98
5a3a9e61-f50e-49ce-9d52-357ede369736	ram.charan@example.com	Ram Charan	2026-08-24 03:10:40.455139	CARD	payment successful	149.98
e70862ca-978f-458f-8bbc-2dc24d12187e	ram.charan@example.com	Ram Charan	2026-08-24 03:10:59.476242	CARD	payment successful	59.99
284d27f7-ca4b-417e-b143-91e5c9fba22e	ram.charan@example.com	Ram Charan	2026-08-24 03:11:41.802444	CARD	payment successful	299.99
30970fc7-0277-4d0c-a795-d73fb7383edf	ram.charan@example.com	Ram Charan	2026-08-24 03:11:47.303854	CARD	payment successful	179.98
a2fbaf87-69f1-444a-a033-faa504a3c473	ram.charan@example.com	Ram Charan	2026-08-25 20:40:31.701431	CARD	payment successful	34.99
a6b9129a-49ce-4f33-87ac-109f770b0376	ram.charan@example.com	Ram Charan	2026-08-25 20:41:04.370415	CARD	payment successful	34.99
c6ab94e8-ebf1-47f0-89fd-fd378b3fa626	ram.charan@example.com	Ram Charan	2026-08-26 02:12:45.541317	CARD	payment successful	329.98
0fbceadd-2d80-43e6-bff5-dfcbeb77dd0b	ram.charan@example.com	Ram Charan	2026-08-26 03:22:48.860237	CARD	payment successful	269.99
42dc5b14-3025-448b-b1e0-1826768ab584	ram.charan@example.com	Ram Charan	2026-08-26 03:53:31.543295	CARD	payment successful	379.98
686ed6ba-bdd3-45b2-9cf6-2b12d7c86a3a	ram.charan@example.com	Ram Charan	2026-08-26 03:54:28.817089	CARD	payment successful	119.98
c0630d4e-2787-4a87-b021-373f1818fdd9	ram.charan@example.com	Ram Charan	2026-08-26 17:14:58.827873	CARD	payment successful	359.98
5f5ed2cc-a628-40e2-90c8-e1af9e3810ed	ram.charan@example.com	Ram Charan	2026-08-26 17:17:46.767834	CARD	payment successful	59.99
33c4e9b9-9ec3-4d1c-8c9b-ca9107921ea1	ram.charan@example.com	Ram Charan	2026-08-26 20:36:50.392034	CARD	payment successful	364.97
8f0b2b4d-2133-483d-a6ba-3b49e7558cd6	manju@gmail.com	manju	2026-08-26 21:22:13.773913	CARD	payment successful	659.88
532f60ef-91a4-43f0-a905-f3327f3cd968	manju@gmail.com	manju	2026-08-26 21:22:55.991127	CARD	payment successful	599.98
1065091c-c491-486f-887b-9e467f3b5adc	manju@gmail.com	manju	2026-08-26 21:57:06.426517	CARD	payment successful	309.98
c4bc167e-44b1-4c37-8744-d63b7c5bcec1	ram.charan@example.com	Ram Charan	2026-08-26 23:09:47.958528	CARD	payment successful	310.00
e74ecd67-980b-4ab9-84c3-08b03cb6d6af	ram.charan@example.com	Ram Charan	2026-08-26 23:10:00.450925	CARD	payment successful	29.97
27c06e88-f632-4150-8515-5729ba114657	ram.charan@example.com	Ram Charan	2026-08-26 23:34:29.118329	CARD	payment successful	99.98
86f79fa3-3636-4bf0-8167-7899364901f2	ram.charan@example.com	Ram Charan	2026-08-27 00:42:43.921924	CARD	payment successful	309.99
1b7dc4d8-cf72-47fe-933e-4f756e74937d	manju@gmail.com	manju	2026-08-27 01:22:00.891667	CARD	payment successful	29.83
e15f4195-404a-4bc3-be93-41538af789c7	manju@gmail.com	manju	2026-08-27 01:22:21.929001	CARD	payment successful	60.00
82f187e1-faca-41e9-8696-ede1ab227ecb	manju@gmail.com	manju	2026-08-27 01:40:51.137869	CARD	payment successful	1539.94
8b5b3f95-eca4-4b11-8d05-7416cf488480	manju@gmail.com	manju	2026-08-27 01:41:08.350477	CARD	payment successful	400.00
72709050-7bae-4e82-93ed-db2d9a433681	manju@gmail.com	manju	2026-08-27 01:41:23.812601	CARD	payment successful	100.00
94c61a95-c721-4030-98f4-afaefeb3d02d	manju@gmail.com	manju	2026-08-27 01:46:45.374072	CARD	payment successful	50.00
120f4d99-0c14-45b3-bfff-6de66f15e956	manju@gmail.com	manju	2026-08-27 01:49:53.436028	CARD	payment successful	100.00
ea492b50-253c-49ac-8f6c-7a221790118b	manju@gmail.com	manju	2026-08-27 01:54:23.763845	CARD	payment successful	159.97
f661af2b-b15c-4992-ab67-eece5151132f	manju@gmail.com	manju	2026-08-27 02:04:08.274433	CARD	payment successful	100.00
d65d8ed0-d8d2-4220-993f-cf74b6407fbd	manju@gmail.com	manju	2026-08-27 02:04:30.211148	CARD	payment successful	200.00
41af15cc-c945-413d-be4e-80ec0f6f3cd4	manju@gmail.com	manju	2026-08-27 02:04:48.45376	CARD	payment successful	200.00
b85faf8b-4071-4f62-87e4-809d75337b5b	manju@gmail.com	manju	2026-08-27 02:05:40.832198	CARD	payment successful	9.99
1423eacc-3696-4b0c-9adb-56693b201832	suraj@gmail.com	suraj km	2026-08-27 02:08:01.426444	CARD	payment successful	250.00
1f9cef4c-d29c-4a27-8036-7bca6d04097f	suraj@gmail.com	suraj km	2026-08-27 02:31:20.29115	CARD	payment successful	800.00
69a33043-994e-44e3-a25c-7ebc439f8ac8	suraj@gmail.com	suraj km	2026-08-27 02:34:14.385632	CARD	payment successful	239.99
26e0fd49-f7c8-4e93-a8c0-69dc0a7ea280	suraj@gmail.com	suraj km	2026-08-27 02:34:33.138256	CARD	payment successful	50.00
831b2a68-eda5-4005-a28d-c3cac46f45b9	suraj@gmail.com	suraj km	2026-08-27 02:52:03.094778	CARD	payment successful	59.98
28494d65-4d45-4fc8-a2ee-16ae180b5a7d	suraj@gmail.com	suraj km	2026-08-27 03:25:50.003812	CARD	payment successful	49.99
beda68cf-5cea-4b66-80c1-98898bc4dda8	anand.manju1@gmail.com	Manju Anand	2026-08-28 03:06:30.120982	CARD	payment successful	629.99
b73d758d-3ec4-485d-9eb0-26a715cf0915	anand.manju1@gmail.com	Manju Anand	2026-08-28 03:06:51.267592	CARD	payment successful	250.00
a9638722-5e7b-4ce2-8dfc-c129ab981f3e	anand.manju1@gmail.com	Manju Anand	2026-09-08 13:35:01.278242	CARD	payment successful	309.93
6289a89c-99da-45ca-8b1c-0baa86824453	anand.manju1@gmail.com	Manju Anand	2026-09-08 13:35:23.676723	CARD	payment successful	50.00
b1db01cd-c4ae-43f4-a12f-9bdd4677e19e	anand.manju1@gmail.com	Manju Anand	2026-09-08 13:47:22.347772	CARD	payment successful	409.97
a57be472-b270-4937-ba4f-f00f533ffc18	anand.manju1@gmail.com	Manju Anand	2026-09-08 13:54:02.947512	CARD	payment successful	30.00
a08d0ec7-468f-4cd6-86d1-cb55996f50a6	anand.manju1@gmail.com	Manju Anand	2026-09-08 15:28:52.02107	CARD	payment successful	150.00
907933e5-276f-4231-a2f4-8778ace1abce	suraj@gmail.com	suraj km	2026-09-08 15:42:08.721543	CARD	payment successful	349.99
57d58684-0b49-4ac9-8a8e-f9b02338e556	suraj@gmail.com	suraj km	2026-09-08 15:42:23.914864	CARD	payment successful	30.00
3803a607-1afd-454a-90ef-8437393e30e1	suraj@gmail.com	suraj km	2026-09-08 15:43:32.535136	CARD	payment successful	30.00
45514040-6fad-441c-a474-41ef2d78e981	anand.manju1@gmail.com	Manju Anand	2026-09-08 17:18:42.5743	CARD	payment successful	99.99
4d627b60-7bc2-4254-982f-70a1592ae333	anand.manjama@gmail.com	manjukanju	2026-09-08 17:21:48.72909	CARD	payment successful	50.00
e32fd0e3-840a-45da-b611-e449798a3572	suraj@gmail.com	suraj km	2026-09-08 17:50:52.132403	CARD	payment successful	150.00
51ceeabf-a29c-4124-8051-4831be5e41d3	suraj@gmail.com	suraj km	2026-09-08 18:24:08.422104	CARD	payment successful	169.99
d5658d18-c85b-4758-9f77-114263a16ef7	suraj@gmail.com	suraj km	2026-09-08 18:26:43.356816	CARD	payment successful	30.00
9555f687-fb95-4f7b-900c-3c72c9536f66	suraj@gmail.com	suraj km	2026-09-08 19:34:37.120485	CARD	payment successful	99.99
f1866166-ec99-4546-a451-bf01f4e08537	suraj@gmail.com	suraj km	2026-09-09 14:54:13.775812	CARD	payment successful	50.00
0a9d90f0-31d2-45f2-87c8-5d0cf5b668ef	anand.manju1@gmail.com	Manju Anand	2026-09-09 14:54:49.345802	CARD	payment successful	50.00
83c36bb9-d082-45af-896f-7bd8d01098d5	suraj@gmail.com	suraj km	2026-09-09 15:06:51.034544	CARD	payment successful	89.99
\.


--
-- Name: order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_item_id_seq', 128, true);


--
-- Name: order_item_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_item_product_id_seq', 21, true);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: order_item fkt4dc2r9nbvbujrljv3e23iibt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fkt4dc2r9nbvbujrljv3e23iibt FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- PostgreSQL database dump complete
--

\unrestrict m0wl0TxL0bR4FVMl3f2UaLhPeaOsm7nac4bI85yIWsPm4fZkXCIO22JnYSlPt40

