--
-- PostgreSQL database dump
--

\restrict bQaE6C5Vqa6udOVmcdH4B8FgCrFcmR54E1e66v4szFkjxCf0fwpesWe7ddFAtiz

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.product DROP CONSTRAINT IF EXISTS product_pkey;
DROP TABLE IF EXISTS public.product;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    category character varying(255),
    description character varying(255),
    name character varying(255),
    price numeric(38,2),
    image_key character varying(255)
);


--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product (id, category, description, name, price, image_key) FROM stdin;
1	Electronics	Ergonomic wireless mouse with silent clicks, adjustable DPI, and USB receiver.	Nova Wireless Mouse	30.00	products/c3697ea3-09da-4088-87c7-8572654bb997-images.jpeg
2	Handbags	Chic pastel pink shoulder bag with gold-tone hardware and an adjustable strap.	Blush Mini Shoulder Bag	200.00	products/871394b5-d1e0-4d7a-ae63-841435750379-il_570xN.4715721698_h4lm.webp
3	Jewelry	Elegant pearl drop earrings with a delicate gold-tone finish for everyday or occasion wear.	Pearl Drop Earrings	50.00	products/58e934b5-502f-45a7-abb0-efee6fd74640-images (1).jpeg
4	Beauty	Hydrating tinted lip oil that leaves lips glossy with a subtle berry finish.	Berry Glow Lip Oil	19.84	products/891aaab8-aad5-46bf-a433-6c198257643d-BerryBlastlipoil-3-_2.webp
5	Home	Floral scented candle with soft cherry blossom and vanilla notes in a minimalist glass jar.	Cherry Blossom Candle	9.99	products/ba9ad638-ef4b-478d-b81c-4a0bab6b9de4-images (2).jpeg
6	Clothing	Lightweight floral midi dress with a flattering waistline and flowy silhouette.	Floral Summer Dress	49.99	products/62054fd7-bd45-467f-8538-c53cd8350a08-images (3).jpeg
7	Clothing	Cozy knit sweater featuring tiny embroidered cherry details.	Cherry Knit Sweater	39.99	products/99d3f123-1188-45b0-8e1a-51f2e4613c07-il_570xN.3662867580_5a6a.webp
8	Electronics	Compact wireless keyboard with rounded keys and a soft pastel design.	Dreamy Wireless Keyboard	49.99	products/01786f1b-a40f-489f-8f56-803a1c2681c2-images (4).jpeg
9	Travel	Slim passport cover with floral detailing and dedicated card slots.	Floral Passport Holder	9.99	products/84d51b2c-49bd-4b3a-8201-040a11f4f2a5-images (5).jpeg
10	Clothing	Limited-edition oversized black T-shirt inspired by the dreamy mood of Radhima, featuring a moonlit silhouette, subtle musical-wave artwork, and “Radhima” typography across the front. Made from soft premium cotton with a relaxed unisex fit.	Radhima Moonlight Oversized T-Shirt	34.99	products/b32ed001-e2a7-49f5-8d4c-3183497d4991-Gemini_Generated_Image_o6ns6mo6ns6mo6ns.jpeg
11	Clothing	A soft blush-pink scarf designed for men, featuring a clean woven finish and lightweight warmth. Easy to pair with coats, jackets, or traditional outfits for an elegant statement look.	Blush Pink Classic Men’s Scarf	20.99	products/801634c5-76a7-40bf-a168-ea126152c57d-EWNn9FAUMAALcdk.jpg
12	Jewelry	A soft blush-pink scarf designed for men, featuring a clean woven finish and lightweight warmth. Easy to pair with coats, jackets, or traditional outfits for an elegant statement look.	Rose Gold Necklace & Earrings Set	39.99	products/2e8f3b47-8b2b-4e36-b8d2-29f62ee6cf1a-maxresdefault.jpg
13	handbags	A sleek and practical men’s handbag crafted with a premium leather finish. Features an adjustable shoulder strap, secure zip closure, and multiple compartments for carrying a phone, wallet, keys, and everyday essentials.	Urban Men’s Crossbody Bag	40.99	products/5e88091f-180c-4ce9-b931-ffe144d7c310-mhl-slingbags-lululemon-0363-688b9dbae5908.avif
14	Home	Minimalist matte ceramic vase with a modern curved design, perfect for flowers, shelves, dining tables, and entryways.	Nordic Ceramic Flower Vase	32.99	products/5584d1cd-c7c6-498c-9d74-946ddbd68bcd-il_1588xN.8472961981_9kqf.webp
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_id_seq', 14, true);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict bQaE6C5Vqa6udOVmcdH4B8FgCrFcmR54E1e66v4szFkjxCf0fwpesWe7ddFAtiz

